---
# tasks file for roles/consul

- name: Install utils
  ansible.builtin.apt:
    name: curl,wget,unzip
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Create group consul
  ansible.builtin.group:
    name: consul
    system: true
    state: present

- name: Create user consul
  ansible.builtin.user:
    name: consul
    system: true
    shell: /sbin/nologin
    state: present

- name: Create directory for consul agent data
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: consul
    group: consul
    recurse: true
  loop:
    - "{{ consul_dir_data }}"
    - "{{ consul_dir_config }}"

- name: Check if consul exists
  ansible.builtin.stat:
    path: "{{ consul_binary_path }}/consul"
  register: __consul_exists

- name: If consul exists get version
  ansible.builtin.shell: "cat /etc/systemd/system/consul.service | grep Version | sed s/'.*Version '//g" # noqa: risky-shell-pipe
  become: true
  register: __consul_get_version
  when: __consul_exists.stat.exists
  changed_when: false

- name: Download consul
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: "{{ consul_binary_path }}"
    remote_src: true
    mode: "0750"
    owner: consul
    group: consul
  when: not __consul_exists.stat.exists or not __consul_get_version.stdout == consul_version

- name: Create service consul for agent
  ansible.builtin.template:
    src: "{{ item.file }}.j2"
    dest: "{{ item.path }}/{{ item.file }}"
    mode: "0750"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  loop:
    - { path: "/etc/systemd/system", file: "consul.service", user: "root" }
    - { path: "{{ consul_dir_config }}", file: "config.json", user: "consul"}
  notify: Reload_daemon_and_restart_consul

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start consul
  ansible.builtin.service:
    name: consul
    state: started
    enabled: true
