- name: Consul services for all servers
  become: true
  hosts: all
  serial: 40
  gather_facts: false
  roles:
    - consul_services
  vars:
    consul_services:
      - {
        name: "node_exporter",
        type: "http",
        check_target: "http://127.0.0.1:9100",
        interval: "10s",
        port: 9100
      }
