password: "{{ vault_unik_password }}"
sudo_nopass: false
use_sudo: true
custom_bashrc: true
ssh_public_key: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINYhunetyxbq4O63mVsokuov/6lAOfLmYocBQ8ZBkXup oki@doki 