---
# defaults file for roles/consul

consul_version: 1.22.0
consul_dir_master_data: ""
consul_dir_data: "{{ consul_dir_master_data }}/var/lib/consul"
consul_dir_config: /etc/consul.d/
consul_binary_path: /usr/local/bin
consul_datacenter: infomaniak
consul_dns_domain: consul
consul_master: false
consul_group: meta-app_consul
